name: Deploy Helm Chart

on:
  push:
    branches:
      - main

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube/
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Deploy with Helm
      run: | 
        helm upgrade --install my-release ./charts/my-app --namespace lucas --create-namespace
        kubectl -n lucas get all


